### ISSUE TITLE
More flexible sorting and grouping within channels

### ISSUE THREAD

**Issue by cleverdevil** [cleverdevil/together#15]
It would be nice to enable the user to choose how they want their channels sorted and grouped when browsing:

* Sorting
  * Chronological by publish date
  * Chronological by "added" date (when the item was discovered by the microsub server)
* Grouping
  * By feed
  * By "post type"

I, personally, like some channels as chronological by publish date (sort of like a traditional "river of news" timeline) and others grouped by source and then sorted chronologically by publish date.

**Comment by aaronpk** [comment]
I'm already planning on making a change to the Microsub server so that newly-added feeds don't fill the whole first page of posts. Basically the first time you add a feed, it will backdate those posts based on the published date. Future posts will work as they currently do, adding to the top of the list.

Assuming that is in place, are you sure you still want the additional sorting features?

**Comment by aaronpk** [comment]
For reference, here is the issue tracking this: https://github.com/aaronpk/Monocle/issues/5

**Comment by cleverdevil** [comment]
For reference, when I add new feeds, I want the newly imported items to respect the publish date, as you suggest above, but I also don't want to "miss" them necessarily, which is why I like having read-state tracking.

In my ideal world, I'd like to be able to decide this when adding a new feed to a channel. Upon adding, I'd like to specify whether or not I want the existing feed items to be imported with an unread state or not.

**Comment by grantcodes** [comment]
Going to close because this is more of a spec issue, than an issue with together
