### ISSUE TITLE
First Prototype Ideas

### ISSUE THREAD

**Issue by grantcodes** [cleverdevil/together#2]
So what are we thinking for a first working prototype type thing?

Based on the wireframe we came up with I think the first step would be to develop a basic functional stream that reads from a parsed feed eg [https://ruby.microformats.io/microformats?utf8=✓&url=https%3A%2F%2Fcleverdevil.io](https://ruby.microformats.io/microformats?utf8=✓&url=https%3A%2F%2Fcleverdevil.io)

Or maybe it would be wiser to try and update woodwind to be more like the wireframe if it has the same end goal.

Personally I'd be happy to have a go at putting something basic together with react if there's no huge objection to that. Then it shouldn't be super difficult for others to contribute and improve.

**Comment by misuba** [comment]
I was about to jump into sketching with ClojureScript and Reagent myself, but while your version of this idea is undoubtedly more practical, I think it might still be premature in either case. There's a lot more to wireframe, such as the flow for following a user or feed.

**Comment by cleverdevil** [comment]
So, I am not opposed to some light prototyping and tinkering. Wireframing is, after all, just one form of prototyping and iterating on an idea. One thing we discussed in the original planning discussion at IWS was that we wanted to first focus on the actual reading experience, and defer on:

* Discovering and following feeds
* Interaction and publishing via Micropub (we will simply outsource these to [Quill](http://quill.p3k.io) for now.
* Any sort of backend (eventually Microsub, which is still in draft form, and has no implementations).

Given that, I think that the single wireframe we have is a decent start. The wireframes I'd like to focus on after this one are the "cards" that represent different types of content – likes, reposts, checkins, notes, articles, photos, etc. But, those will simply slot into the "stream" / "timeline" view in the center, and I actually think that tinkering with that in a prototype is a reasonable way to go.

For my part, I've been quickly hacking together a script that uses [mf2py](https://github.com/tommorris/mf2py) to fetch a bunch of sample data from a small sample set of sources, and then dump it to disk as JSON-encoded items. I figure we can use this for a prototype to load sources from, rather than depending on a Microsub server. I'll try and toss that up here later today, if I have time!

**Comment by cleverdevil** [comment]
Okay, I pushed the script up. Rough, but helpful to build up a little data store to use for tinkering.

**Comment by grantcodes** [comment]
Nice that'll be super useful! And good incentive for me to fix my microformats markup 😅 

I have an absolute minimum react app at the moment that you can just give a url and parses it through some super dirty hacks. But it works ok for testing and should be relatively easy for everyone to contribute to.

![image](https://user-images.githubusercontent.com/3390268/27616197-c9fefe5a-5b62-11e7-907a-c980df3b4f9b.png)

I can tidy it up slightly and submit a PR if this is the route we want to go down.

From a technical and design point of view handling the fact that microformats is very optional and in arrays is probably going to be a challenge. I imagine there will be a lot of if statements, fallbacks and loops.

**Comment by cleverdevil** [comment]
Awesome, @grantcodes. That looks like a good start. Feel free to submit a PR.

Upon further reading of the [Microsub spec draft](https://indieweb.org/Microsub-spec), it appears that a Microsub endpoint will actually return posts in [JF2 format](http://dissolve.github.io/jf2/), not in the JSON-representation output by my script. It turns out that the JF2 format is *much* more strict, which should make life a ton easier. I'll try and update my script to output JF2 somehow.

In the meantime, it's likely best to make the prototype expect data in JF2.

**Comment by aaronpk** [comment]
The goal with Microsub is to make building readers like this super easy, which is why you see the jf2 it uses being much more strict than the parsed mf2. Basically I expect to use the JSON format that XRay returns for this. Feel free to plug URLs in to https://xray.p3k.io/ for testing. XRay is also available as a PHP library https://github.com/aaronpk/XRay

**Comment by grantcodes** [comment]
Yas, jf2 will make life so much easier! 🙏 

I think for prototyping sake it would be really nice to have something like the script @cleverdevil made create a jf2 and have it hosted online somewhere (with CORS enabled) then that can be the "backend" and work on building out the UI based on real world content.
