### ISSUE TITLE
Hyperlink author name and photo to author URL

### ISSUE THREAD

**Issue by aaronpk** [cleverdevil/together#37]
Right now the name and photo are not links, and I keep trying to click them

**Comment by cleverdevil** [comment]
I am going to try and do this, since it seems like an approachable way for me to actually contribute to the code.

It appears that the underlying Avatar component for React that we are using doesn't actually have this capability built-in:

http://www.material-ui.com/#/components/avatar

That said, I am guessing I can still make it happen with some fiddling. Wish me luck :)
